train:
  _target_: utils.evaluator.MultipleEvaluator
  evaluators: ["MIOU_Evaluator", "LossAccuracyByClassEvaluator"]


test: 
  _target_: utils.evaluator.MultipleEvaluator
  evaluators: ["MIOU_Evaluator", "LossAccuracyByClassEvaluator"]