name: PCM

params:
  _target_: models.PCM.PCM.PointMambaSegmentation
  in_channels: 5
  num_classes: ${dataset.params.num_classes}
  embedding_size: ${.encoder.embed_dim} # 2 x 16, 16 is x2 dim_expansion
  hidden_dim: 32
  encoder: 
    _target_: models.PCM.PCM.PointMambaEncoder
    in_channels: ${..in_channels}
    embed_dim: 32


optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0

warmup_epochs: 1

batch_size: 1

# scheduler: cosine
scheduler: step
step_size: 150
gamma: 0.5

