name: PCM3

params:
  _target_: models.segmentation.SegmentationHead
  in_channels: 5
  num_classes: ${dataset.params.num_classes}
  embedding_size: 64 # 16 x 16, 16 is x2 dim_expansion
  hidden_dim: 32
  encoder: 
    _target_: models.PCM.PCM.PointMambaEncoder
    in_channels: ${..in_channels}
    embed_dim: 8
    mamba_blocks: [3, 3, 3]
    dim_expansion: [2,2,2]
    pre_blocks: [2,2,2]
    pos_blocks: [2,2,2]
    k_neighbors: [12,12,12]
    k_strides: [1,1,1]
    reducers: [2,2,2]
    mamba_layers_orders: ["xyz", "xzy", "yxz",
                          "xyz", "xzy", "yxz",
                          "xyz", "xzy", "yxz",
                          ]
    parallel_multihead: True


optimizer:
  _target_: torch.optim.Adam
  lr: 0.002
  weight_decay: 0.0
clip_gradients: True

warmup_epochs: 1

batch_size: 4

# scheduler: cosine
scheduler: step
step_size: 60
gamma: 0.5

