name: nuscenes_lidar

params: 
  _target_: dataloader.nuscenes.NuScenesLidarDataset
  path: ./data/nuscenes
  num_classes: 32
  # max_points: 12000
  max_samples: 1000
  train_version: v1.0-trainval
  # test_version: v1.0-test
  # train_version: v1.0-mini
  test_version: v1.0-mini
