name: nuscenes_lidar_v1.0

params: 
  _target_: dataloader.nuscenes.NuScenesLidarDataset
  path: ./data/nuscenes
  num_classes: 32
  # max_points: 12000
  max_samples: 100
  test_split: 0.1
  train_version: v1.0-trainval
  test_version: v1.0-trainval
