defaults: 
  - _self_
  - model: PCM
  - dataset: nuscenes_lidar_v1.0 
  - loss: cross_entropy
  - evaluator: loss_accuracy_evaluator
  
seed: 0
num_epochs: 100
log_frequency: 50
evaluate_frequency: 1

print: True
use_wandb: True
log_model: False

num_workers: 4
num_threads: 4

project_name: 3DMamba

wandb:
  tags: []
  project: point-net
  group: 'tmp'
  name: '${model.name}_${dataset.name}_${now:%Y-%m-%d_%H-%M-%S}'
  entity: 'vlr-3dmamba'

workdir: 
  root: '/home/${oc.env:USER}/data/${project_name}'
  name: 'models/${model.name}/${wandb.group}/${now:%Y-%m-%d_%H-%M-%S}'
  checkpoint_path: '${workdir.root}/${workdir.name}/ckpt.pth'

hydra:
  run:
    dir: /home/${oc.env:USER}/data/${project_name}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
